version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: public/docker/Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - "../../:/var/www/html/"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=sistema_agencia
      - MYSQL_USER=agencia_user
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: