<?php
class BodyHome {
    public function render() {
        echo '<body class="d-flex flex-column h-100">';
        echo '<main class="flex-shrink-0">';
        echo '<!-- Header-->';
        echo '<header class="bg-dark py-5">';
        echo '<div class="container px-5">';
        echo '<div class="row gx-5 align-items-center justify-content-center">';
        echo '<div class="col-lg-8 col-xl-7 col-xxl-6">';
        echo '<div class="my-5 text-center text-xl-start">';
        echo '<h1 class="display-5 fw-bolder text-white mb-2">A Bootstrap 5 template for modern businesses</h1>';
        echo '<p class="lead fw-normal text-white-50 mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!</p>';
        echo '<div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">';
        echo '<a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>';
        echo '<a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '<div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>';
        echo '</div>';
        echo '</div>';
        echo '</header>';
        echo '<!-- Features section-->';
        echo '<section class="py-5" id="features">';
        echo '<div class="container px-5 my-5">';
        echo '<div class="row gx-5">';
        echo '<div class="col-lg-4 mb-5 mb-lg-0">';
        echo '<h2 class="fw-bolder mb-0">A better way to start building.</h2>';
        echo '</div>';
        echo '<div class="col-lg-8">';
        echo '<div class="row gx-5 row-cols-1 row-cols-md-2">';
        echo '<div class="col mb-5 h-100">';
        echo '<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>';
        echo '<h2 class="h5">Featured title</h2>';
        echo '<p class="mb-0">Paragraph of text beneath the heading to explain the heading. Here is just a bit more text.</p>';
        echo '</div>';
        echo '<div class="col mb-5 h-100">';
        echo '<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-building"></i></div>';
        echo '<h2 class="h5">Featured title</h2>';
        echo '<p class="mb-0">Paragraph of text beneath the heading to explain the heading. Here is just a bit more text.</p>';
        echo '</div>';
        echo '<div class="col mb-5 mb-md-0 h-100">';
        echo '<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>';
        echo '<h2 class="h5">Featured title</h2>';
        echo '<p class="mb-0">Paragraph of text beneath the heading to explain the heading. Here is just a bit more text.</p>';
        echo '</div>';
        echo '<div class="col h-100">';
        echo '<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-toggles2"></i></div>';
        echo '<h2 class="h5">Featured title</h2>';
        echo '<p class="mb-0">Paragraph of text beneath the heading to explain the heading. Here is just a bit more text.</p>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</section>';
        echo '<!-- Testimonial section-->';
        echo '<div class="py-5 bg-light">';
        echo '<div class="container px-5 my-5">';
        echo '<div class="row gx-5 justify-content-center">';
        echo '<div class="col-lg-10 col-xl-7">';
        echo '<div class="text-center">';
        echo '<div class="fs-4 mb-4 fst-italic">"Working with Start Bootstrap templates has saved me tons of development time when building new projects! Starting with a Bootstrap template just makes things easier!"</div>';
        echo '<div class="d-flex align-items-center justify-content-center">';
        echo '<img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />';
        echo '<div class="fw-bold">';
        echo 'Tom Ato';
        echo '<span class="fw-bold text-primary mx-1">/</span>';
        echo 'CEO, Pomodoro';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '<!-- Blog preview section-->';
        echo '<section class="py-5">';
        echo '<div class="container px-5 my-5">';
        echo '<div class="row gx-5 justify-content-center">';
        echo '<div class="col-lg-8 col-xl-6">';
        echo '<div class="text-center">';
        echo '<h2 class="fw-bolder">From our blog</h2>';
        echo '<p class="lead fw-normal text-muted mb-5">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque fugit ratione dicta mollitia. Officiis ad.</p>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '<div class="row gx-5">';
        echo '<div class="col-lg-4 mb-5">';
        echo '<div class="card h-100 shadow border-0">';
        echo '<img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />';
        echo '<div class="card-body p-4">';
        echo '<div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>';
        echo '<a class="text-decoration-none link-dark stretched-link" href="#!">';
        echo '<h5 class="card-title mb-3">Blog post title</h5>';
        echo '</a>';
        echo '<p class="card-text mb-0">Some quick example text to build on the card title and make up the bulk of the card\'s content.</p>';
        echo '</div>';
        echo '<div class="card-footer p-4 pt-0 bg-transparent border-top-0">';
        echo '<div class="d-flex align-items-end justify-content-between">';
        echo '<div class="d-flex align-items-center">';
        echo '<img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />';
        echo '<div class="small">';
        echo '<div class="fw-bold">Kelly Rowan</div>';
        echo '<div class="text-muted">March 12, 2023 &middot; 6 min read</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '<div class="col-lg-4 mb-5">';
        echo '<div class="card h-100 shadow border-0">';
        echo '<img class="card-img-top" src="https://dummyimage.com/600x350/adb5bd/495057" alt="..." />';
        echo '<div class="card-body p-4">';
        echo '<div class="badge bg-primary bg-gradient rounded-pill mb-2">Media</div>';
        echo '<a class="text-decoration-none link-dark stretched-link" href="#!">';
        echo '<h5 class="card-title mb-3">Another blog post title</h5>';
        echo '</a>';
        echo '<p class="card-text mb-0">This text is a bit longer to illustrate the adaptive height of each card. Some quick example text to build on the card title and make up the bulk of the card\'s content.</p>';
        echo '</div>';
        echo '<div class="card-footer p-4 pt-0 bg-transparent border-top-0">';
        echo '<div class="d-flex align-items-end justify-content-between">';
        echo '<div class="d-flex align-items-center">';
        echo '<img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />';
        echo '<div class="small">';
        echo '<div class="fw-bold">Josiah Barclay</div>';
        echo '<div class="text-muted">March 23, 2023 &middot; 4 min read</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</div>';
        echo '</section>';
        echo '</main>';
        echo '</body>';
    }
}

$bodyHome = new BodyHome();
$bodyHome->render();
?>