# Usar la imagen oficial de PHP con Apache
FROM php:8.2-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copia el archivo de configuración de Apache
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Habilita el módulo de reescritura de Apache
RUN a2enmod rewrite

# Copiar el código fuente al contenedor
COPY ../../../ /var/www/html/

# Establecer permisos correctos
RUN chown -R www-data:www-data /var/www/html/

# Exponer el puerto 80
EXPOSE 80